### ISSUE TITLE
npm start: code ELIFECYCLE; errorno 1

### ISSUE THREAD

**Issue by albertStaalburger** [P3trur0/vagrant-electron#1]
Thank you for the box and scripts, but I hit a brick wall. 

I am trying to get `quick-start` up and running in your box.
I followed your post: [https://flatmap.it/2016/10/25/vagrant-electron/](url) to get the box set-up.
System info:
Box: Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-141-generic x86_64)
Node: v8.2.1
Npm: v5.3.0

I have read through other similar errors and searched the web for quite a few hours.
I know it is not my `Node` version that is the issue as in most other cases.

When running `npm start` I get the following error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-02-19T21_08_55_663Z-debug.log
```
Opening the log file gives me:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/vagrant/.nvm/versions/node/v8.2.1/bin/node',
1 verbose cli   '/home/vagrant/.nvm/versions/node/v8.2.1/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /home/vagrant/.nvm/versions/node/v8.2.1/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/Code/electron-quick-start/node_modules/.bin:/home/vagrant/.nvm/versions/node/v8.2.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/vagrant/Code/electron-quick-start
10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/vagrant/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/home/vagrant/.nvm/versions/node/v8.2.1/lib/node_modules/npm/lib/utils/spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd /home/vagrant/Code/electron-quick-start
16 verbose Linux 3.13.0-141-generic
17 verbose argv "/home/vagrant/.nvm/versions/node/v8.2.1/bin/node" "/home/vagrant/.nvm/versions/node/v8.2.1/bin/npm" "start"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I am at a loss as to what is causing this error.
Any guidance or pointers would be appreciated...

**Comment by ubaldop** [comment]
Hi @albertStaalburger, thank you for pointing out this issue! Tonight I'll give it a look and try to come with a proper solution to your problem :smiley_cat:

**Comment by ubaldop** [comment]
Hi @albertStaalburger, I am trying to reproduce your problem, but on my machine the quick start project starts without any error. I downgraded my NPM and Node versions to the same you mention above, but again the electron-quick-start project is working in my case.

Did you try to clone and launch another Electron project to see if the problem is still there?

Please, let me know.

Cheers!

**Comment by albertStaalburger** [comment]
I tried another project but could not get it working.
I am really green with regards to Electron.

I think I might have not set up my package.json correctly.
I have a different working directory to that of yours. My project lies in a
code directory.

I will try adjusting the scripts > start and see if that isn't causing the
issue.

Thank you for the help.

**Comment by ubaldop** [comment]
Hi Albert, you're welcome. The following are the steps I performed yesterday night trying to reproduce the problem:

1. Cloned this project
2. Launch `vagrant up`
3. Launch `vagrant ssh`
3.a Downgrade Node version to **8.2.1** doing `nvm install 8.2.1`
4. Invoke `cd /vagrant`
5. Invoke `git clone https://github.com/electron/electron-quick-start.git`
6. Invoke `cd electron-quick-start`
7. Launch `npm install`
8. Launch `npm start`

I was unable to reproduce the problem :/

**Comment by albertStaalburger** [comment]
Sorry for the slow reply.
I will follow the steps again, this time not changing the node version to see if that makes a difference.

I am on MacOS. Maybe there is something preventing it form functioning correctly.
I see that the scripts executing the `apt` commands as the default user, I will add `sudo` option to my script. 
Maybe that is causing the problems.

**Comment by ubaldop** [comment]
@albertStaalburger please keep me updated about that :smiley:
