### ISSUE TITLE
windows/virtualbox: no internet connection

### ISSUE THREAD

**Issue by paolocaminiti** [P3trur0/vagrant-electron#2]
Running via virtualbox on windows 10 from git bash:

I got no internet connection, this fixes the problem:

https://stackoverflow.com/questions/18457306/how-to-enable-internet-access-inside-vagrant

```
config.vm.provider 'virtualbox' do |vb|
  ...
  vb.customize ['modifyvm', :id, '--cableconnected1', 'on']
  ...
```

You may consider to have it as default or add it to the README, thanks for the box!

**Comment by ubaldop** [comment]
Hi @paolocaminiti thank you for the suggestion :) I'll add this parameter after my vacation time. Indeed at the moment I am on a mobile phone and not able to do any fix.
Have a nice day!

**Comment by ubaldop** [comment]
Hi @paolocaminiti your suggestion has been added to `Vagrantfile` through #3. Thank you!
