### ISSUE TITLE
Authentication failure

### ISSUE THREAD

**Issue by wyxos** [P3trur0/vagrant-electron#4]
I am using Windows 10 and trying to get your vagrant configuration working but I keep getting the message "Warning: Authentication failure. Retrying...".

I do have ssh keys already set up on the root folder i.e user/username/.ssh/id_rsa which is used by my homestead environment for laravel projects. I am not sure how to configure your Vagrant settings to work around this issue.

**Comment by wyxos** [comment]
I deleted the insecure_private_key in .vagrant.d on my machine, ran vagrant up again and it's now working.

**Comment by wyxos** [comment]
Doing the above actually broke my homestead vagrant.

**Comment by ubaldop** [comment]
@jyrula so is the issue still there?

**Comment by wyxos** [comment]
Hi, sorry for the delay. Yes the issue persists. Here are the steps I've gone through taking into account the following specs:
- Windows 10 Pro 64
- Vagrant 2.2.3
- VirtualBox 5.6.2

Steps:
- git clone https://github.com/P3trur0/vagrant-electron
- cd vagrant-electron
- vagrant start

When vagrant attempts to set up SSH, I get the following:
```
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection reset. Retrying...
    default: Warning: Connection aborted. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
    default: Warning: Authentication failure. Retrying...
```

And it keeps throwing this error non stop. Sorry if this is not an issue related to the box. But I found it even odd to see that another user did use this box on Windows and had no issue. I am assuming maybe, he didn't have homestead set up at global level. This causes my .vagrant.d folder to already have an insecure_private_key file which is eventually a replicate of the id_rsa I have in .ssh under my root user folder on Windows.
From what I read, I assume I should do something in the provision for it to know to use the same SSH? would that be the cause of being unable to access the machine?

**Comment by ubaldop** [comment]
Hi @jyrula, yes, I think you should do something in the provisioning `Vagrantfile`, I mean something like this:

```
 #path of your homestead environment SSH
  config.ssh.private_key_path = "~/.ssh/id_rsa" 
 #agent forwarding
  config.ssh.forward_agent = true
```
Take a look at [this StackOverflow](https://stackoverflow.com/a/23554973/5775077) reply, that seems addressing the same your problem you're facing on your environment.

**Comment by wyxos** [comment]
Hi, thanks for the above. I encountered the suggested solution but it didn't work. But that one additional step from the answer you linked "Don't forget to add your public key to ~/.ssh/authorized_keys on the Vagrant VM" did resolve the issue. I am now able to vagrant up without further errors. Though I feel this is wrong in the sense that: a user already using another vagrant machine and being on Windows trying this box out would eventually have to:
- vagrant up once and encounter the error
- exit the process and vagrant ssh
- copy the public keys in and exit
- vagrant halt, amend the VagrantFile and then vagrant up
I am guessing there might be a way to automate this copying of the public key from host to guest but I'll have to do some research.

Right now I have another issue where I am unable to run npm install on the guest machine without encountering errors "ETXTBSY: text file is busy". I assume this is again another Windows issue... I am severely getting tired of how everything gets painful on Windows. I'll be focusing on getting npm to run first on this, then I'll get back here if I find a suggestion for automating the public key copying.

**Comment by ubaldop** [comment]
Hi @jyrula thank you for your detailed scenario description. Indeed, running this VM on Windows sounds quite annoying. However, please keep me updated about your progress with it. I mean, given your description we could either improve the documentation or find some automatic mechanism to get rid of all these issues. :muscle:

**Comment by wyxos** [comment]
Hi @P3trur0, thanks again for your help on this. I encountered a situation where I messed up the box while attempting to resolve the issue with NPM, so I decided to destroy the machine but, then realized I would have to go through the steps above manually again...

So I gave up on the npm issue and now trying to figure out how homestead achieves this process automatically. Today I was in a situation where I tried two instance of homestead at a time, and had no issue when it came to the SSH part (I mean it does seem to sort it out on its own despite that the logs felt like it was doing something with the host insecure_private_key).

So far, what I am reading seems to be in Ruby? (.rb file)
```
        # Configure The Public Key For SSH Access
        if settings.include? 'authorize'
            if File.exists? File.expand_path(settings["authorize"])
                config.vm.provision "shell" do |s|
                    s.inline = "echo $1 | grep -xq \"$1\" /home/vagrant/.ssh/authorized_keys || echo \"\n$1\" | tee -a /home/vagrant/.ssh/authorized_keys"
                    s.args = [File.read(File.expand_path(settings["authorize"]))]
                end
            end
        end

        # Copy The SSH Private Keys To The Box
        if settings.include? 'keys'
            if settings["keys"].to_s.length == 0
                puts "Check your Homestead.yaml file, you have no private key(s) specified."
                exit
            end
            settings["keys"].each do |key|
                if File.exists? File.expand_path(key)
                    config.vm.provision "shell" do |s|
                        s.privileged = false
                        s.inline = "echo \"$1\" > /home/vagrant/.ssh/$2 && chmod 600 /home/vagrant/.ssh/$2"
                        s.args = [File.read(File.expand_path(key)), key.split('/').last]
                    end
                else
                    puts "Check your Homestead.yaml file, the path to your private key does not exist."
                    exit
                end
            end
        end
```

I am trying to make sense of this and apply it on the VagrantFile of your box. This will take me a bit as my experience with Vagrant is limited as the homestead file seems to take care of all of the overheads vagrant involves.

**Comment by wyxos** [comment]
So my current VagrantFile looks like this
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME_MACHINE = "electron.box"

# Setup root script
$baseScript = <<SCRIPT
		echo "I am provisioning a #{HOSTNAME_MACHINE} machine"
		cd /home/vagrant
		add-apt-repository ppa:git-core/ppa
		apt-get update
		apt-get install -y vim git curl
		echo "Installing required graphical libraries for Electron"
		apt-get install -y libgtk2.0-0
		apt-get install -y libxss1
	    apt-get install -y GConf2
		apt-get install -y libnss3
		# apt-get install -y libcanberra-gtk*
SCRIPT

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
	hostname = HOSTNAME_MACHINE
	locale = "en_GB.UTF.8"

    # Allow SSH Agent Forward from The Box
    config.ssh.forward_agent = true

	config.vm.provision "shell" do |s|
        s.inline = "echo $1 | grep -xq \"$1\" /home/vagrant/.ssh/authorized_keys || echo \"\n$1\" | tee -a /home/vagrant/.ssh/authorized_keys"
        s.args = [File.read(File.expand_path("~/.ssh/id_rsa.pub"))]
    end

    # Copy The SSH Private Keys To The Box
    config.vm.provision "shell" do |s|
        s.privileged = false
        s.inline = "echo \"$1\" > /home/vagrant/.ssh/$2 && chmod 600 /home/vagrant/.ssh/$2"
        s.args = [File.read(File.expand_path("~/.ssh/id_rsa")), "~/.ssh/id_rsa".split('/').last]
    end

	# Box
	config.vm.box = "ubuntu/trusty64"
	# Shared folders
	config.vm.synced_folder ".", "/vagrant", owner: "vagrant", group: "vagrant"

	# Removes "stdin: is not a tty" annoyance as per
	# https://github.com/SocialGeeks/vagrant-openstack/commit/d3ea0695e64ea2e905a67c1b7e12d794a1a29b97
	config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

	#setup X-Forwarding
	config.ssh.forward_x11 = true

	# Provision basic tools
	config.vm.provision :shell, :inline => $baseScript
	config.vm.provision :shell, :path => "scripts/setup.sh", privileged: false

	config.vm.provider "virtualbox" do |vb|
		vb.customize	[
			"modifyvm", :id,
			'--cableconnected1', 'on',
			"--memory", 1024,
			]

		# Allow the creation of symlinks for nvm
		# http://blog.liip.ch/archive/2012/07/25/vagrant-and-node-js-quick-tip.html
		vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant","1"]
	end
end
```

But that doesn't solve the issue. I still keep getting the Authentication failure and it doesn't seem to have copied the public key. Though, vagrant ssh-config seems to reference the right/insecure_private_key

**Comment by ubaldop** [comment]
@jyrula yep, that's Ruby.

**Comment by wyxos** [comment]
Sorry, I've moved away from using the above solution due to evolution in technology since. Closing the issue as assuming it's no more relevant.
